### ISSUE TITLE
Orchestration templates

### ISSUE THREAD

**Issue by theerror** [rhtconsulting/cfme-rhconsulting-scripts#75] opened 2016-10-31 12:47 UTC
How about "Orchestration templates"? 

Right now, I was find out, that those are no exported/imported at all? Is it somehow bug, or it's not implemented?

**Comment by branic** [comment] 2016-11-01 02:11
@theerror 

The lack of import/export of orchestration templates is not a bug. At this point a script has not been written to perform the export/import.

It is on the radar to look into writing a rake script, but I don't have a timeframe.

Regards,
Brant

**Comment by theerror** [comment] 2016-11-01 18:56
Sad to hear... 

Anyway thank you for reply.

**Comment by tobmat** [comment] 2017-03-01 19:30
Any update on a timeframe for import/export of orchestration templates?  Thank you!

**Comment by jeffmcutter** [comment] 2018-01-27 01:20
Merged 103 which provides support for orchestration templates.

**Closed by jeffmcutter** 2018-01-27 01:20 UTC
